ansible_become_pass: ENC[AES256_GCM,data:vXY6pYASiCE=,iv:2Xa8m/0/bCjp4rO4wdvcu8jJuI/9WR5Jt8w1xuDPgW4=,tag:hblkKN06AiiuS8jiZYR9tg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u8qter24nmxgaxw6s8nqmjwrypgfhtxk0d5jtkfsjpqmmq2t4a2qre6qgv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeXN5d2d3S2pQSUxJNEk3
            MW1qWGE5SVVlT1d5OGpIS0F6cVJkSXo2dzA4CnJSdmQ1d2RUZ1lKVFdKdCs4VUh0
            UFpZR0JBTEhXalNWcTJ4cUtzSk1tQmsKLS0tIC9oRHp4OEdJcFVpYWxIQ1JVbGly
            ejNvK1dzQTJpQkxGZHR0TGZKL3QvSzgKpp9JmZgFZ76il4Z+utHzGZnYeqaSwkh9
            m6ARADhSzqslRpFMw004qMmWyVcflUW1bsHEK5Ghk64q2pq036ZrIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-07T05:03:57Z"
    mac: ENC[AES256_GCM,data:ZGHWWnJW5RpW3HmVHf5x025W7SkF2QZflN0+Tkcy6LW4g+rmK2VQyfvrtxqTlOUzGF4hG6kRzYDHc1l0ju7zi+qh6UBQL7DJcn/NnLSR/qAoXYs29SEq1nl4VFL04HJkf7PgJaZH6f2KnFGcQ1OgJscyBJYbqvdOMcVM5xpFYA0=,iv:NuOei+8XDfXSpHi18NtHZZlGYmvHkIzG/sF+//3rOVM=,tag:3cxSKNw9pTi0FguQCTF9YA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
