apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Aj7HpO6FCCdWlV4yB8FLb0QsG3Bj2moJ,iv:DKKVUV3QQfatUHahiKFhm3LUA7JrLAORQZQe+44JRAs=,tag:f6vAyvtxtgUGvKOl45Q3Jg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u8qter24nmxgaxw6s8nqmjwrypgfhtxk0d5jtkfsjpqmmq2t4a2qre6qgv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQ2FFWXZscHMvUUxPbEh1
            TEtUVjg2MVhOemczTkxrT0dPazVxZ0QyU0VNCnZGMElCVGJzSTIyMVYvUk12eDAv
            UGNteUFzK0xTaC9udmEyb0Q4cHNpeGcKLS0tIGtCb0Z2bUkyUU5HaEt5UlRxR0h0
            cHZ0Wk16Mmduak54UW0yUjRKVmt3elkKw9fkZypLTAY9rI/s6Lz58HHA7DfNcoyo
            fj/QIt4cLJh9axBimP6TNxM5KyzVFAJLe0A40aApyAcKMQgG1djI1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-07T05:04:29Z"
    mac: ENC[AES256_GCM,data:xxMBU5RMgVZT6tj6XkE5mIGww7L5ofKbT0xf0qtSVBgmPIE5jNuWwVM99KBGXXdW9k+wGe6IPJfbjqz8W1chtAj3JxlEcIBQaBgrIRe9G2lM5VthvpwxVqnQEeJtl1bFGoLATTJkeqpEmTNhAmz44GcGy9+6BKZjgfYEoz34/OU=,iv:L3PJrIqWwWITR1o4KmMFhpfUcJWsW39v6WFABVhS/Oo=,tag:fVoXeCVzH3bGDM4ExQK+bg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
