apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:/+SXivMkRxRD07Q2SpbqYT5GYEQEHyb1yTtkqgcIjGxpV9QqChYHow==,iv:56hIx/jVdh0+ip08kPkreYTjMHOQhKA0GM/AaZPxrZI=,tag:en3G/tUiQ/VfIQeGm1gjKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u8qter24nmxgaxw6s8nqmjwrypgfhtxk0d5jtkfsjpqmmq2t4a2qre6qgv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVnFLNVBrdmZRNzFrdUk5
            OFlBVHJkWU85RUtGN0NjVDczbWZLRGFwcHdBClo2WHowS3ZVTDAxUG5aTldqTndu
            MjJnSjRLMGJxS1cxSTNINVlFUENGOTgKLS0tIEZacFg4Rk96S0xHMk8rQWFXTG9L
            aUdrOVhOclRUTHR3czRueCtwZFVGOWMKBK7h/hosQ2l7fcVLJWXJAn0kA5gf2Fs5
            a60h1+ADKaXsfobie0WdlR3yGzS6JPna5TEemVSsgGWd+vFP3ORrVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-07T05:02:02Z"
    mac: ENC[AES256_GCM,data:Zdp9Yg7iLOluWaadTku7sz4LvojPVHHmMGio5uPqyDr6MNV0FszXa+FgVW0FbjosReH+8YqFA6vPJnB/6lZvHZ0Qgk96fuf2HQIiQPwFVsrgBP+/rRy4ijWXrrKnICTDcRwIGsWTxfwyzaZS93DL8FstGIuoWulX5AV/Wfu97uY=,iv:ZA8Bhsd16NZCXoKo3OG0G5Ez8W/AE4U/gNSJulZAuf0=,tag:qPAAJlpDrQ4ncSCEIlNRwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
