apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:QMjuSaATsh57Efr9ytgjxjc5xkulpLCd7c1bhHDJZITlL+oNr1cbrw==,iv:AhHqxzWiVo6QrOWujO3vOnIeLIC0IuDhnMyi71EaP3Y=,tag:n2pj4ewaU8AWtlF522ECeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u8qter24nmxgaxw6s8nqmjwrypgfhtxk0d5jtkfsjpqmmq2t4a2qre6qgv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObXNRa2p1NmpzZTRCbVlj
            Z2lteExMTUNid0owUTlXUnE4S3N1akRTQ1hzCklnME5ZUnB5OWNrVFRXa0pycUQ1
            NDFON3RKSzVKeHZoQmRtdUthK3ZFV2cKLS0tIHAvOVZEL3dPMHdEQWlMcDVMejN4
            eWppYWErMUhScnNrbVdta0N4alVVQ0EKkgeghwHs1lvo4qfs/6DO66IqRI6zhmY3
            LlLaGas8WA/cKyU5bmpjAoX1InWYFK31Jf3EcoAb1SfV9BcYu2KbJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-07T00:03:06Z"
    mac: ENC[AES256_GCM,data:koq09zhYT1GdzX8NVunFwymfNw1XS2hswEi9q/VYpwSBM8Heq5raPkHZGQoNwNNmPrjT0J6kQhVuvCaPoMF2oCb9KFkjeq4t/HK+GL/WsnVfn54Ctgz/6kBBbp0y8C5lT/hTXBh0NR/ShXa1sB6UskWIU7ANcXcNsgxOQnCbiBQ=,iv:EjQyZ8LjCUmo9rGVffafO8dPUkCQpfqP36/B9vYi82s=,tag:lXOPYvBe4578YPFd/uWMbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
