apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:SnAnom95eM6gueMf,iv:lWDXh3mGjUTNRwHeFik0WJSKah+CHIZa4ubsClMVwgI=,tag:A16OCi2PDRW+eWc87gpY3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u8qter24nmxgaxw6s8nqmjwrypgfhtxk0d5jtkfsjpqmmq2t4a2qre6qgv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YVFXT2ZZSU1QdllCa0Zs
            NXFpSGlzdThaTEFDNlY0TkZWZk9rYTJFOGpNCm9qT282b0FFS09vVVE5WXZDNFpM
            YVdhWFB6bDBuNFp3QkoxLzFHeit2QkUKLS0tIHYySVMzVC9hL2hCbWVlUjQ4WTRw
            bFcvSXU2SC9GNTgrUGI5UnBMQURIQ0kK3Q2ubqEZdOmpuNpQxKbvZLBs4DCyEmvE
            p2KbKDH6wo/1ToiyMVnm/BtLndw1aL2riXXbAzLl1ly/FkteipBl5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-07T00:03:06Z"
    mac: ENC[AES256_GCM,data:RZJicabYP/fCKrFWOke3lpP8YYJbTzPDYKyMtPfPMZHchycUNXkj+HmGraVGh46LFwvJKesx3h3b5Qt61o1DDNDISE6Hbpj05OEpRR330XrshLLFC2XaHA/3CI+AoqIC+4dP76aBP3BBe8Bsmi1PPIvRorYNVw74/OlJWCerNWw=,iv:UhmxDTA7JJMGpCZ7HH9RUGMEbOGqR5Sa2+0tqBu2HiA=,tag:ykTJNxkOLEXF9sLMI3lv8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
